In [1]:
import pandas as pd
import numpy as np 
from sklearn import linear_model

In [2]:
df = pd.read_csv('./homeprices_withMultipleVariable.csv')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

**Data Preprocessing**

In [3]:
bedrooms_median = df.bedrooms.median()

In [4]:
df.fillna({
    'bedrooms':bedrooms_median,
},inplace=True)
## we can do it like this also df.bedroom.fillna(bedrooms_median,inplace=True)

In [5]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540384

In [9]:
reg.predict([[3000,3,40]])

/home/cyborg_prisoner/.local/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [10]:
reg.predict([[3000,3,5]])

/home/cyborg_prisoner/.local/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([611518.37838246])

In [11]:
import pickle

In [12]:
## save model with pickle
with open('model_pickle','wb') as f :
    pickle.dump(reg,f)

In [13]:
with open('model_pickle','rb') as f :
    model = pickle.load(f)

In [15]:
model.predict([[3000,3,5]])
## we have got the same result as before
## what's the benefit we can now share the trained model

/home/cyborg_prisoner/.local/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([611518.37838246])

In [19]:
## with joblib
import joblib 
joblib.dump(reg,'model_joblib') 

['model_joblib']

In [20]:
model = joblib.load('model_joblib')
model.predict([[3000,3,5]])

/home/cyborg_prisoner/.local/lib/python3.10/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([611518.37838246])