In [1]:
import numpy as np
a = np.array([1,3,4,5])
print(a)
print(a[0])
print(a[2])

[1 3 4 5]
1
4


In [2]:
import time 
import sys

l = range(1000)
print(sys.getsizeof(5)*len(l))
a = np.arange(1000)
print(a.size*a.itemsize)

28000
8000


In [3]:
##checking required time
size = 1000000
l1 = range(size)
l2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
res1 = [(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000,"ms")
start = time.time()
res2 =  a1 + a2
print((time.time()-start)*1000,"ms")

130.11550903320312 ms
3.3838748931884766 ms


In [4]:
a1 = np.array([1,2,3])
a2 = np.array([3,4,3])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)

[4 6 6]
[-2 -2  0]
[3 8 9]
[0.33333333 0.5        1.        ]


In [5]:
a = np.array([[1,2],[2,3],[4,3]])
## to know dimension
print(a.ndim)
## item size in bytes
print(a.itemsize)
## default data type
print(a.dtype)
## modify type with dtype
a = np.array([[1,2],[2,3],[4,3]],dtype=np.float128)
print(a.dtype)
print(a)

2
8
int64
float128
[[1. 2.]
 [2. 3.]
 [4. 3.]]


In [6]:
a = np.array([[1,3,4],[1,3,43],[3,2,4]],dtype=complex)
print(a.dtype)
## print each dimension shape
print(a.shape)

complex128
(3, 3)


In [15]:
a = np.zeros((1,8)) ## inside define the shape
print(a)
print(a.shape)
a = np.zeros(8)
print(a)
print(a.shape)
a = np.ones((8,))
print(a)
a = np.ones((8,1))
print(a)
a = np.arange(1,6)
print(a)
a = np.arange(1,20.2,.2)
print(a)
print(a.size)
a = a.reshape(12,8)
print(a)
a = a.ravel() ## forces to be in one dim
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]]
(1, 8)
[0. 0. 0. 0. 0. 0. 0. 0.]
(8,)
[1. 1. 1. 1. 1. 1. 1. 1.]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[1 2 3 4 5]
[ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.
 12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8
 15.  15.2 15.4 15.6 15.8 16.  16.2 16.4 16.6 16.8 17.  17.2 17.4 17.6
 17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4 19.6 19.8 20. ]
96
[[ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4]
 [ 2.6  2.8  3.   3.2  3.4  3.6  3.8  4. ]
 [ 4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6]
 [ 5.8  6.   6.2  6.4  6.6  6.8  7.   7.2]
 [ 7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8]
 [ 9.   9.2  9.4  9.6  9.8 10.  10.2 10.4]
 [10.6 10.8 11.  11.2 11.4 11.6 11.8 12. ]
 [12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6]
 [13.8 14.  1

In [16]:
a = a.reshape(8,12)
print(a.min())
print(a.max())
print(a.min(axis=0),'column wise min')
print(a.max(axis=0),'column wise max')
print(a.min(axis=1),'row wise min')
print(a.max(axis=1),'column wise max')
print(a.sum())
print(a.sum(axis=0),'column wise sum')
print(a.sum(axis=1),'row wise sum')

1.0
19.999999999999996
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2] column wise min
[17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4 19.6 19.8 20. ] column wise max
[ 1.   3.4  5.8  8.2 10.6 13.  15.4 17.8] row wise min
[ 3.2  5.6  8.  10.4 12.8 15.2 17.6 20. ] column wise max
1007.9999999999999
[75.2 76.8 78.4 80.  81.6 83.2 84.8 86.4 88.  89.6 91.2 92.8] column wise sum
[ 25.2  54.   82.8 111.6 140.4 169.2 198.  226.8] row wise sum


In [17]:
a= np.array([1,2,4,8])
print(np.sqrt(a))
a = np.arange(1,13,2)
a = a.reshape(3,2)
b = np.arange(2,14,2)
b = b.reshape(3,2)
print(a+b)
print(a-b)
print(a*b)
b = b.reshape(2,3)
print(a.dot(b)) ## matrix product
b = b.reshape(3,2)
print(a/b)

[1.         1.41421356 2.         2.82842712]
[[ 3  7]
 [11 15]
 [19 23]]
[[-1 -1]
 [-1 -1]
 [-1 -1]]
[[  2  12]
 [ 30  56]
 [ 90 132]]
[[ 26  34  42]
 [ 66  90 114]
 [106 146 186]]
[[0.5        0.75      ]
 [0.83333333 0.875     ]
 [0.9        0.91666667]]


In [18]:
## slicing 1dim np array like slicing a list and also can use negative indexing
a = np.arange(1,20.2,.4)
a = a.reshape(6,8)
print(a)
print(a[1,2])
print(a[0,1])
print(a[0:2,0:3])
print(a[:,0:2]*a[:,2:4])

[[ 1.   1.4  1.8  2.2  2.6  3.   3.4  3.8]
 [ 4.2  4.6  5.   5.4  5.8  6.2  6.6  7. ]
 [ 7.4  7.8  8.2  8.6  9.   9.4  9.8 10.2]
 [10.6 11.  11.4 11.8 12.2 12.6 13.  13.4]
 [13.8 14.2 14.6 15.  15.4 15.8 16.2 16.6]
 [17.  17.4 17.8 18.2 18.6 19.  19.4 19.8]]
4.999999999999999
1.4
[[1.  1.4 1.8]
 [4.2 4.6 5. ]]
[[  1.8    3.08]
 [ 21.    24.84]
 [ 60.68  67.08]
 [120.84 129.8 ]
 [201.48 213.  ]
 [302.6  316.68]]


In [19]:
for c in a.flat :
    print(c)
a

1.0
1.4
1.7999999999999998
2.1999999999999997
2.5999999999999996
2.9999999999999996
3.3999999999999995
3.7999999999999994
4.199999999999999
4.6
4.999999999999999
5.399999999999999
5.799999999999999
6.199999999999999
6.599999999999999
6.999999999999998
7.399999999999999
7.799999999999999
8.2
8.599999999999998
8.999999999999998
9.399999999999999
9.799999999999997
10.199999999999998
10.599999999999998
10.999999999999998
11.399999999999999
11.799999999999997
12.199999999999998
12.599999999999998
12.999999999999996
13.399999999999997
13.799999999999997
14.199999999999998
14.599999999999998
14.999999999999996
15.399999999999997
15.799999999999997
16.199999999999996
16.599999999999994
16.999999999999996
17.399999999999995
17.799999999999997
18.199999999999996
18.599999999999994
18.999999999999996
19.399999999999995
19.799999999999997


array([[ 1. ,  1.4,  1.8,  2.2,  2.6,  3. ,  3.4,  3.8],
       [ 4.2,  4.6,  5. ,  5.4,  5.8,  6.2,  6.6,  7. ],
       [ 7.4,  7.8,  8.2,  8.6,  9. ,  9.4,  9.8, 10.2],
       [10.6, 11. , 11.4, 11.8, 12.2, 12.6, 13. , 13.4],
       [13.8, 14.2, 14.6, 15. , 15.4, 15.8, 16.2, 16.6],
       [17. , 17.4, 17.8, 18.2, 18.6, 19. , 19.4, 19.8]])

In [20]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print(b)
print(np.vstack((a,b)),'vertical stack') ## no of columns must be same
print(np.hstack((a,b)),'horizontal stack') ## no of rows must be same

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] vertical stack
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]] horizontal stack


In [21]:
a = np.arange(30).reshape(2,15)
print(a)
## horizontal spliting
r = np.hsplit(a,3) ## column no er theke beshi houya jabe na
print(r[0])
print(r[1])
print(r[2])
r = np.vsplit(a,2) ## row no er theke beshi howya jabe na
print(r[0])
print(r[1])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [22]:
a = np.arange(12).reshape(3,4)
b = a > 4
print(b)
print(a[b])
a[b] = -1
print(a)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


In [23]:
a= np.arange(12).reshape(3,4)
for row in a :
    print(row)
for element in a.flatten():
    print(element,end=" ")
print()
## use of nditer
## order C  row wise
## order F column wise
for x in np.nditer(a,order='C'):
    print(x) 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 4 5 6 7 8 9 10 11 
0
1
2
3
4
5
6
7
8
9
10
11


In [28]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [29]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x
print(a) 

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [30]:
b = np.arange(3,15,4).reshape(3,1)
b 

array([[ 3],
       [ 7],
       [11]])

In [31]:
for x,y in np.nditer([b,a]):
    print(x,y)

3 0
3 1
3 4
3 9
7 16
7 25
7 36
7 49
11 64
11 81
11 100
11 121
